---
title: "Measurement Model Scaling and Identification"
author: "William Murrah"
date: ''
output:
  html_document:
    fig_height: 3
    fig_width: 5
  pdf_document:
    fig_height: 3
    fig_width: 5
  word_document:
    fig_height: 3
    fig_width: 5
---


```{r, include=FALSE}
# Don't delete this chunk if you are using the mosaic package
# This loads the mosaic and dplyr packages
require(mosaic)
```

```{r, include=FALSE}
# Some customization.  You can alter or delete as desired (if you know what you are doing).

# This changes the default colors in lattice plots.
trellis.par.set(theme=theme.mosaic())  

# knitr settings to control how R chunks work.
require(knitr)
opts_knit$set(root.dir ="../../../../")
opts_chunk$set(
  echo = FALSE,
  comment = NULL,
  tidy=FALSE,     # display code as typed
  size="small"    # slightly smaller font for code
)
# This loads the mosaic data sets.  (Could be deleted if you are not using them.)
require(mosaicData)  
require(lavaan)
require(ztable)
options(ztable.type = 'html', ztable.zebra.color="platinum")
library(DiagrammeR)
```

## 
```{r, echo = TRUE}
library(lavaan)

##Prepare data with sufficient statisitics##
mymeans<-matrix(c(3.06893, 2.92590, 3.11013), ncol=3,nrow=1)
mysd<-c(0.84194,0.88934,0.83470)
mat <- c(1.00000,
         0.55226, 1.00000,
         0.56256, 0.66307, 1.00000)
mycor <- getCov(mat, lower = TRUE)
##Transform correlation matrix to covariance matrix using information above##
myvarcov <- outer(mysd, mysd, FUN="*")
mycov <- mycor * myvarcov

rownames(mycor) <-c( "Glad", "Cheerful", "Happy")
colnames(mycor) <-c( "Glad", "Cheerful", "Happy")

rownames(mycov) <-c( "Glad", "Cheerful", "Happy")
colnames(mycov) <-c( "Glad", "Cheerful", "Happy")
mynob<-823
```


```{r, results = 'asis'}
cr <- ztable(mycor, zebra = 2)
tab <- data.frame(Mean = round(mymeans[1, ], 3), SD = round(mysd, 3), 
                  Var = round(mysd*mysd, 3))

pt <- t(cbind(mycor, tab))
ztable(pt, zebra = 2, caption = "Descriptive Statistics")

```

### Fundamental SEM equation
$$
\Sigma = \Lambda \Psi \Lambda + \Theta \tag{1}
$$


### Latent Cheer with one indicator

```{r}

```

```
# Mplus file
l.cheer.inp
```
```{r}
grViz("
digraph Cheer {

node [shape = circle]
Positive;

node [shape = box]
Cheer;

# Edges

Positive -> Cheer [label = <&nbsp;&lambda;>];
Positive:n -> Positive:n [dir=both, label = <&psi;>,position = N]
Cheer:s -> Cheer:s [dir=both, label = <&theta;>]
}  
")
```


### Measurement Model: 3 indicators

 using correlations only (instead of variance/covariance matirx)

```{r}
mod1<-'Positive =~ 1*Cheerful
Positive~~Positive
Cheerful~~0*Cheerful'
#Save output to fit1##
fit1<-cfa(mod1, sample.cov=mycov, sample.nobs = mynob, sample.mean=mymeans, 
          std.lv=F)

##Request for summary of output##


summary(fit1, fit.measures=T)
```

```{r, echo = TRUE}
cat(file = 'topics/2_MeasurementModel/2b_ConfirmatoryFactorAnalysis/mplus/l.cheer.out')

```

```{r}
grViz("
    
digraph CFA {

node [shape = circle]
Positive;

node [shape = box]
Glad; Cheer; Happy;

# Edges
Positive -> Glad [label = <&nbsp;&lambda;<sub>1</sub>>];
Positive -> Cheer [label = <&nbsp;&lambda;<sub>2</sub>>];
Positive -> Happy [label = <&nbsp;&lambda;<sub>3</sub>>];
Positive:n -> Positive:n [dir=both, label = <&psi;>]
Glad:s -> Glad:s [dir=both, label = <&theta;<sub>1</sub>>]
Cheer:s -> Cheer:s [dir=both, label = <&theta;<sub>2</sub>>]
Happy:s -> Happy:s [dir=both, label = <&theta;<sub>3</sub>>]

	{rank = same; Positive;}
	{rank = same; Glad; Cheer; Happy;}
}  
")

```
